name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run:   <a href="https://www.carshopper.com/" style="color:#FF0000;">car shopper</a>
    - name: Run a multi-line script
      run: link
        echo Add other actions to build,
        echo test, and deploy your project.
